### ISSUE TITLE
Wiki: Wrong alias for UserApi

### ISSUE THREAD

**Issue by MTEXX** [MercierCorentin/laravel-nextcloud-api-client#3]
`'aliases' => [
    // ...
    'GroupApi' => MercierCorentin\Nextcloud\Facades\UserApi::class,
]`

should be

`'aliases' => [
    // ...
    'UserApi' => MercierCorentin\Nextcloud\Facades\UserApi::class,
]`

at https://github.com/MercierCorentin/laravel-nextcloud-api-client/wiki/Users

**Comment by MercierCorentin** [comment]
Thanks for reporting this typo! I edited the wiki.
